# Generated by Django 4.0.2 on 2022-02-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(blank=True, default='img/Default_Image.png', null=True, upload_to='img/'),
        ),
    ]
