# Generated by Django 4.0.2 on 2022-02-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('locked', 'locked'), ('unlocked', 'unlocked')], default='user', max_length=20),
        ),
    ]
